apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: app-server
        image: nguyenphuc0406/spring-boot:1.0.1
        imagePullPolicy: IfNotPresent
        
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
        ports:
        - containerPort: 8083
          
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: mysql-db-url
                key: url
---
apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
  - name: http
    port: 8083
    targetPort: 80
    protocol: TCP
    nodePort: 31080



     
