apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
    
spec:
  selector:
    matchLabels:
      app: spring-app
      
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: mysql-demo
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password #root
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-db-url
                key: database #thuctap                
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: username #root              
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: password #root
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: "myvol"
            mountPath: /var/lib/mysql
      volumes:
        - name: myvol
          hostPath:
            path: "/home/phucnd/test_docker/demo_vds/database_kube"


